Repository particle-iot/particle-usb, pull requests merged in 2019-02, with the labels that each got.

#4 Basic mesh device API
  .travis.yml
  src/cellular-device.js
  src/cloud-device.js
  src/config.js
  src/device-base.js
  src/device.js
  src/mesh-device.js
  src/network-device.js
  src/particle-usb.js
  src/request.js
  src/result.js
  src/usb-device-node.js
  src/wifi-device.js
  test/cellular-device.js
  test/device-base.js
  test/mesh-device.js
Labels: feature, ready to merge

#3 WebUSB support
  .travis.yml
  package.json
  src/usb-device-webusb.js
  webpack.config.js
Labels: feature, ready to merge

#5 Fix openDeviceById() and leaveListeningMode()
  package.json
  src/device-base.js
  src/device-type.js
  src/device.js
  src/usb-device-node.js
  src/usb-device-webusb.js
  test/cellular-device.js
  test/device-base.js
  test/integration/cellular-device.js
  test/integration/device-base.js
  test/integration/mesh-device.js
  test/mesh-network-diagnostics.js
  test/support/fake-usb.js
  test/support/index.js
Labels: bug

#6 Use forked node-usb
  .gitignore
  .npmignore
  .travis.yml
  RELEASE.md
  package-lock.json
  package.json
  test/integration/cellular-device.js
  test/integration/device-base.js
  test/integration/mesh-device.js
  test/support/index.js
Labels: enhancement

#8 Improve error reporting
  src/device-base.js
  src/device-type.js
  src/error.js
  src/particle-usb.js
  src/usb-device-node.js
  test/device-base.js
  test/integration/mesh-device.js
  test/support/fake-usb.js
Labels: enhancement
